spring.application.name=unifood-backend

spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=${SUPABASE_AUTH_ISSUER}
spring.security.oauth2.resourceserver.jwt.audiences=authenticated
